steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args: ['gcloud', 'iam', 'service-accounts', 'add-iam-policy-binding', 
      'ecommerce-app-350710@appspot.gserviceaccount.com', 
      '--member=serviceAccount:65293551526@cloudbuild.gserviceaccount.com', 
      '--role=roles/iam.serviceAccountUser', 
      '--project=ecommerce-app-350710']
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: 'gcloud'
    args:
    - "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy"
    # args: [
    #     "-c",
    #     "PROJECT_ID=ecommerce-app-350710",
    #     'PROJECT_NUMBER=$(gcloud projects list \
    #     --format="value(projectNumber)" \
    #     --filter="projectId=${PROJECT_ID}")',
    #     'gcloud iam service-accounts add-iam-policy-binding \
    #     ${PROJECT_ID}@appspot.gserviceaccount.com \
    #     --member=serviceAccount:${PROJECT_NUMBER}@cloudbuild.gserviceaccount.com \
    #     --role=roles/iam.serviceAccountUser \
    #     --project=${PROJECT_ID}',
    #     "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy",
    #   ]
    secretEnv: ["DB_PW_PROD", "INSTANCE_CONNECTION_NAME", "JWT_SECRET_PROD"]

availableSecrets:
  secretManager:
    - versionName: projects/65293551526/secrets/ECOMMERCE_DB_PW_ENV/versions/latest
      env: "DB_PW_PROD"
    - versionName: projects/65293551526/secrets/ECOMMERCE_INSTANCE_CONNECTION_NAME/versions/latest
      env: "INSTANCE_CONNECTION_NAME"
    - versionName: projects/65293551526/secrets/ECOMMERCE_JWT_SECRET/versions/latest
      env: "JWT_SECRET_PROD"
